replicaCount: 1
fullnameOverride: opencti-ci

env:
  APP__ADMIN__EMAIL: admin@opencti.io
  APP__ADMIN__PASSWORD: test
  APP__BASE_PATH: "/"
  APP__HEALTH_ACCESS_KEY: f93747ff-2ea1-4717-900c-9df20b8e4429
  APP__TELEMETRY__METRICS__ENABLED: true
  APP__GRAPHQL__PLAYGROUND__ENABLED: false
  APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION: false
  ELASTICSEARCH__ENGINE_SELECTOR: elk
  ELASTICSEARCH__URL: http://opencti-ci-elasticsearch:9200
  MINIO__ENDPOINT: opencti-ci-minio
  RABBITMQ__HOSTNAME: opencti-ci-rabbitmq
  RABBITMQ__PORT_MANAGEMENT: 15672
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: user
  REDIS__HOSTNAME: opencti-ci-redis-master
  REDIS__MODE: single
  REDIS__PORT: 6379

testConnection: false

secrets:
  APP__ADMIN__TOKEN: "b1976749-8a53-4f49-bf04-cafa2a3458c1"
  RABBITMQ__PASSWORD: ChangeMe

envFromSecrets:
  APP__ADMIN__TOKEN:
    name: opencti-ci-credentials
    key: APP__ADMIN__TOKEN
  OPENCTI_TOKEN:
    name: opencti-ci-credentials
    key: APP__ADMIN__TOKEN
  RABBITMQ__PASSWORD:
    name: opencti-ci-credentials
    key: RABBITMQ__PASSWORD

connectors:
- name: alienvault
  enabled: true
  replicas: 1
  serviceAccount:
    create: true
    name: ci-sa
    automountServiceAccountToken: true
  readyChecker:
    enabled: true
    retries: 30
    timeout: 10
  deploymentAnnotations:
    ci: "true"
  podAnnotations:
    ci: "true"
  env:
    CONNECTOR_CONFIDENCE_LEVEL: ""
    CONNECTOR_ID: ""
    CONNECTOR_UPDATE_EXISTING_DATA: ""
    CONNECTOR_LOG_LEVEL: ""
    ALIENVAULT_BASE_URL: ""
    ALIENVAULT_API_KEY: ""
    ALIENVAULT_TLP: ""
    ALIENVAULT_CREATE_OBSERVABLES: ""
    ALIENVAULT_CREATE_INDICATORS: ""
    ALIENVAULT_PULSE_START_TIMESTAMP: ""
    ALIENVAULT_REPORT_TYPE: ""
    ALIENVAULT_REPORT_STATUS: ""
    ALIENVAULT_GUESS_MALWARE: ""
    ALIENVAULT_GUESS_CVE: ""
    ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES: ""
    ALIENVAULT_ENABLE_RELATIONSHIPS: ""
    ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES: ""
    ALIENVAULT_INTERVAL_SEC: ""
    CONNECTOR_NAME: "AlienVault"
    CONNECTOR_SCOPE: "alienvault"
    CONNECTOR_TYPE: EXTERNAL_IMPORT
  envFromSecrets:
    OPENCTI_TOKEN:
      name: opencti-ci-credentials
      key: OPENCTI_TOKEN

serviceMonitor:
  enabled: false

autoscaling:
  enabled: true

worker:
  enabled: true

  autoscaling:
    enabled: true

elasticsearch:
  fullnameOverride: opencti-ci-elasticsearch
  master:
    resourcesPreset: "medium"
  data:
    resourcesPreset: "medium"

minio:
  fullnameOverride: opencti-ci-minio

rabbitmq:
  fullnameOverride: opencti-ci-rabbitmq
  auth:
    existingPasswordSecret: opencti-ci-credentials
    existingSecretPasswordKey: RABBITMQ__PASSWORD
    erlangCookie: b25c953e-2193-4b8e-9f3b-9a3a5ba76d75

redis:
  fullnameOverride: opencti-ci-redis
