{{- if .Values.worker.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opencti.fullname" . }}-worker
  labels:
    opencti.component: worker
    {{- include "opencti.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      opencti.component: worker
      {{- include "opencti.selectorLabels" . | nindent 6 }}
  {{- if .Values.worker.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.worker.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.worker.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
